### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [14]:
import numpy as np

In [19]:
# vector 1
import random
vector_1 = np.array([random.uniform(0, 1) for i in range(10)])
print (vector_1)
print(f"Розмір вектора 1: {vector_1.shape}")

# vector 2
vector = np.random.rand(10)
print (vector)
print(f"Розмір вектора 2: {vector.shape}")


[0.84366525 0.79451839 0.46106667 0.02606873 0.86169201 0.28750472
 0.93758247 0.59248807 0.23758743 0.61437082]
Розмір вектора 1: (10,)
[0.31407049 0.38803286 0.42752075 0.91877551 0.30885719 0.94573142
 0.87316033 0.54940793 0.52755492 0.08653307]
Розмір вектора 2: (10,)


In [9]:
# Матриця 3x3
matrix = np.array([
    [11, 20, 29],
    [14, 23, 32],
    [17, 26, 35]
])

print("\nМатриця:")
print(matrix)


Матриця:
[[11 20 29]
 [14 23 32]
 [17 26 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [20]:
# 1
vector_plus10 = np.round(vector + 10, 2)

print("Вектор + 10:")
print(vector_plus10)

Вектор + 10:
[10.31 10.39 10.43 10.92 10.31 10.95 10.87 10.55 10.53 10.09]


In [22]:
# 2
matrix_x2 = matrix * 2

print(matrix_x2)

[[22 40 58]
 [28 46 64]
 [34 52 70]]


In [23]:
# 3
vector_sqrt = vector ** 2

print("\nВектор у квадраті:")
print(vector_sqrt)


Вектор у квадраті:
[0.09864027 0.1505695  0.18277399 0.84414843 0.09539276 0.89440793
 0.76240897 0.30184908 0.27831419 0.00748797]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [24]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [25]:
# Задані дві матриці A і B розмірностями 3x2 та 2х3.
# Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю result_matrix на екран.

# при множенні матриць кількість стовпців нової матриці визначає кількість рядків першої матриці, тому будемо множити В*А.
result_matrix = np.dot(B, A)

print("result_matrix (2x2):")
print(result_matrix)


result_matrix (2x2):
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [28]:
# Заданий вектор C розмірністю 2х1.
# Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на вектор C і який результат буде.
# А потім виконайте множення і виведіть результат на екран.

# print(C)
print(np.dot(result_matrix, C))

[[0.5202]
 [0.2846]]


In [30]:
# Задана матриця D розмірністю 2х2.
# Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите result_matrix на матрицю D і який результат буде.
# А потім виконайте множення і виведіть результат на екран.

print(D)
print(np.dot(result_matrix, D))

[[0 1]
 [1 0]]
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [31]:
# 1
print(result_matrix.T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [32]:
# 2
print("\nvector:")
print(vector)
print(f"Розмір: {vector.shape}")

print("\nТранспонований vector:")
print(vector.T)
print(f"Розмір: {vector.T.shape}")


vector:
[0.31407049 0.38803286 0.42752075 0.91877551 0.30885719 0.94573142
 0.87316033 0.54940793 0.52755492 0.08653307]
Розмір: (10,)

Транспонований vector:
[0.31407049 0.38803286 0.42752075 0.91877551 0.30885719 0.94573142
 0.87316033 0.54940793 0.52755492 0.08653307]
Розмір: (10,)


Змін не видно)

In [33]:
# 3
column_vector = np.expand_dims(vector, axis = 1)
print("\ncolumn_vector (після expand_dims):")
print(column_vector)
print(f"Розмір: {column_vector.shape}")


column_vector (після expand_dims):
[[0.31407049]
 [0.38803286]
 [0.42752075]
 [0.91877551]
 [0.30885719]
 [0.94573142]
 [0.87316033]
 [0.54940793]
 [0.52755492]
 [0.08653307]]
Розмір: (10, 1)


In [34]:
# 4
print("\nТранспонований column_vector:")
print(column_vector.T)
print(f"Розмір: {column_vector.T.shape}")


Транспонований column_vector:
[[0.31407049 0.38803286 0.42752075 0.91877551 0.30885719 0.94573142
  0.87316033 0.54940793 0.52755492 0.08653307]]
Розмір: (1, 10)
